permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: X
  email: vampiregod1996@gmail.com
  link: http://www.abegger.com/
  weibo: 
  github: http://github.com/vampiregod1996

# 站点信息
title: X博客 
description: X博客
url: http://www.abegger.com/
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://cedvq.img46.wal8.com/img46/529870_20151010163008/144446599032.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-65166654-1
  url: http://www.abegger.com/

# disqus 设置
disqus:
  shortname: beggar